# Generated by Django 6.0.5 on 2026-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, max_length=100, verbose_name='Доступные размеры'),
        ),
    ]
