# Generated by Django 6.0.5 on 2026-07-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
