# Generated by Django 6.0.5 on 2026-05-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_visible_to_user',
            field=models.BooleanField(default=True, verbose_name='Виден пользователю'),
        ),
    ]
